"""add scenario ownership

Revision ID: 785e0929440e
Revises: 5a350af36181
Create Date: 2026-09-29 01:22:37.176785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785e0929440e'
down_revision: Union[str, Sequence[str], None] = '5a350af36181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_assets_scenario_id_scenarios', 'scenarios', ['scenario_id'], ['id'])

    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_edges_scenario_id_scenarios', 'scenarios', ['scenario_id'], ['id'])

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_findings_scenario_id_scenarios', 'scenarios', ['scenario_id'], ['id'])

    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_remediation_actions_scenario_id_scenarios', 'scenarios', ['scenario_id'], ['id'])

    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_vulnerabilities_scenario_id_scenarios', 'scenarios', ['scenario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vulnerabilities_scenario_id_scenarios', type_='foreignkey')
        batch_op.drop_column('scenario_id')

    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_remediation_actions_scenario_id_scenarios', type_='foreignkey')
        batch_op.drop_column('scenario_id')

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_findings_scenario_id_scenarios', type_='foreignkey')
        batch_op.drop_column('scenario_id')

    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_constraint('fk_edges_scenario_id_scenarios', type_='foreignkey')
        batch_op.drop_column('scenario_id')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assets_scenario_id_scenarios', type_='foreignkey')
        batch_op.drop_column('scenario_id')
    # ### end Alembic commands ###
