"""test

Revision ID: d1080d27637f
Revises: 
Create Date: 2026-09-28 12:29:25.239814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1080d27637f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('WORKSTATION', 'WEB_SERVER', 'APP_SERVER', 'DATABASE', 'IDENTITY_PROVIDER', 'CLOUD_STORAGE', 'API_GATEWAY', 'DOMAIN_CONTROLLER', name='assettype'), nullable=False),
    sa.Column('criticality', sa.Float(), nullable=False),
    sa.Column('environment', sa.Enum('PRODUCTION', 'STAGING', 'DEVELOPMENT', 'DMZ', 'INTERNAL', name='environment'), nullable=False),
    sa.Column('network_zone', sa.Enum('EXTERNAL', 'DMZ', 'APP_TIER', 'DB_TIER', 'MANAGEMENT', name='networkzone'), nullable=False),
    sa.Column('is_entry_point', sa.Boolean(), nullable=False),
    sa.Column('is_crown_jewel', sa.Boolean(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cve_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='vulnerabilityseverity'), nullable=False),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('known_exploited', sa.Boolean(), nullable=False),
    sa.Column('attack_vector', sa.Enum('NETWORK', 'ADJACENT', 'LOCAL', 'PHYSICAL', name='attackvector'), nullable=True),
    sa.Column('attack_complexity', sa.Enum('LOW', 'HIGH', name='attackcomplexity'), nullable=True),
    sa.Column('privileges_required', sa.Enum('NONE', 'LOW', 'HIGH', name='privilegesrequired'), nullable=True),
    sa.Column('user_interaction', sa.Enum('NONE', 'REQUIRED', name='userinteraction'), nullable=True),
    sa.Column('remediation_effort', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_id'), 'vulnerabilities', ['id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('vulnerability_id', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REMEDIATED', 'SUPPRESSED', 'IN_PROGRESS', name='findingstatus'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_id'), 'findings', ['id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('edge_type', sa.Enum('EXPLOITS', 'CAN_REACH', 'LATERAL_MOVEMENT', 'PRIVILEGE_ESCALATION', 'CREDENTIAL_ACCESS', 'TRUSTED_ACCESS', name='edgetype'), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('traversal_cost', sa.Float(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_id'), 'edges', ['id'], unique=False)
    op.create_table('remediation_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_type', sa.Enum('PATCH_VULNERABILITY', 'REMOVE_VULNERABILITY', 'DISABLE_SERVICE', 'REMOVE_NETWORK_PATH', 'SEGMENT_NETWORK', 'RESTRICT_PORT', 'REMOVE_TRUST_RELATIONSHIP', 'REDUCE_PRIVILEGE', 'CHANGE_ACCESS_POLICY', 'ISOLATE_ASSET', name='remediationactiontype'), nullable=False),
    sa.Column('target_asset_id', sa.String(), nullable=True),
    sa.Column('target_finding_id', sa.String(), nullable=True),
    sa.Column('target_edge_id', sa.String(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('implementation_complexity', sa.String(), nullable=False),
    sa.Column('downtime_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['target_edge_id'], ['edges.id'], ),
    sa.ForeignKeyConstraint(['target_finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_actions_id'), 'remediation_actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_actions_id'), table_name='remediation_actions')
    op.drop_table('remediation_actions')
    op.drop_index(op.f('ix_edges_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_findings_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_vulnerabilities_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
