import type {
  ExplanationClaimResponse,
  ExplanationResponse,
} from '../../types/api';
import { Card, CardHeader, CardBody, Badge } from '../../components/ui';

const STATUS_COPY: Record<
  ExplanationResponse['status'],
  { title: string; description: string; variant: 'success' | 'warning' | 'critical' }
> = {
  AVAILABLE: {
    title: 'AI-generated explanation',
    description: 'Produced by the configured AI provider and validated against backend evidence.',
    variant: 'success',
  },
  FALLBACK: {
    title: 'Deterministic explanation — AI provider unavailable',
    description:
      'This text was NOT generated by an AI model. It is a deterministic template rendered from backend evidence.',
    variant: 'warning',
  },
  UNAVAILABLE: {
    title: 'AI explanation unavailable',
    description: 'The provider could not produce an explanation and no fallback content is available.',
    variant: 'critical',
  },
};

function EvidenceRefs({ refs }: { refs: ExplanationClaimResponse['evidence_refs'] }) {
  if (refs.length === 0) return null;
  return (
    <div className="mt-1.5 flex flex-wrap gap-1.5">
      {refs.map((r) => (
        <span
          key={r.ref_id}
          className="font-mono text-xs bg-[var(--color-bg-tertiary)] px-1.5 py-0.5 rounded"
          title={`${r.source_path} = ${String(r.value ?? 'n/a')}`}
        >
          {r.ref_id}: {r.source_path} = {String(r.value ?? 'n/a')}
        </span>
      ))}
    </div>
  );
}

function ClaimCard({ claim }: { claim: ExplanationClaimResponse }) {
  const variant = claim.type === 'FACT' ? 'default' : claim.type === 'INTERPRETATION' ? 'warning' : 'none';
  return (
    <div className="rounded-md border border-[var(--color-border-primary)] bg-[var(--color-bg-secondary)] p-3">
      <Badge variant={variant}>{claim.type}</Badge>
      <p className="mt-1.5 text-sm text-[var(--color-text-primary)]">{claim.statement}</p>
      <EvidenceRefs refs={claim.evidence_refs} />
    </div>
  );
}

function Section({ title, claims, emptyText }: { title: string; claims: ExplanationClaimResponse[]; emptyText: string }) {
  return (
    <section>
      <h3 className="text-xs font-semibold uppercase tracking-wider text-[var(--color-text-muted)] mb-2">
        {title} ({claims.length})
      </h3>
      {claims.length === 0 ? (
        <p className="text-sm text-[var(--color-text-muted)]">{emptyText}</p>
      ) : (
        <div className="space-y-2">
          {claims.map((c, i) => (
            <ClaimCard key={i} claim={c} />
          ))}
        </div>
      )}
    </section>
  );
}

/** Renders a backend ExplanationResponse verbatim — no frontend rewriting of claims. */
export function ExplanationResult({ explanation }: { explanation: ExplanationResponse }) {
  const status = STATUS_COPY[explanation.status];
  return (
    <div className="space-y-6">
      <Card>
        <CardBody>
          <div className="flex flex-wrap items-center gap-2">
            <Badge variant={status.variant}>{explanation.status}</Badge>
            <Badge variant="default">origin: {explanation.origin}</Badge>
            <Badge variant="default">{explanation.explanation_type}</Badge>
          </div>
          <h2 className="mt-2 text-lg font-semibold text-[var(--color-text-primary)]">{status.title}</h2>
          <p className="mt-1 text-sm text-[var(--color-text-secondary)]">{status.description}</p>
        </CardBody>
      </Card>

      <Card>
        <CardHeader><h2 className="section-title">Summary</h2></CardHeader>
        <CardBody>
          {explanation.summary.statement ? (
            <>
              <p className="text-sm text-[var(--color-text-primary)]">{explanation.summary.statement}</p>
              <EvidenceRefs refs={explanation.summary.evidence_refs} />
            </>
          ) : (
            <p className="text-sm text-[var(--color-text-muted)]">No summary available.</p>
          )}
        </CardBody>
      </Card>

      <Card>
        <CardHeader><h2 className="section-title">Details</h2></CardHeader>
        <CardBody className="space-y-5">
          <Section title="Key factors" claims={explanation.key_factors} emptyText="No key factors returned." />
          <Section title="Impact" claims={explanation.impact} emptyText="No impact claims returned." />
          <Section title="Changes" claims={explanation.changes} emptyText="No change claims returned." />
          <Section title="Limitations" claims={explanation.limitations} emptyText="No limitations returned." />
        </CardBody>
      </Card>
    </div>
  );
}
